name: Build and Deploy
env:
  AWS_DEFAULT_REGION: "ap-southeast-2"
on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: git clone the repo
      uses: actions/checkout@v2

    - name: prep nodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Serverless Framework
      run: npm install -g serverless

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id     :  ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key :  ${{ secrets.AWS_SECRET_KEY }}
        aws-region            :  ${{ env.AWS_DEFAULT_REGION }}

    - name: Install NPM dependencies
      run : npm install

    - name: Deploy Lambda functions
      env :
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
      run : sls deploy
