name: Test
env:
  AWS_DEFAULT_REGION: "ap-southeast-2"
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: git clone the repo
        uses: actions/checkout@v2

      - name: prep nodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Inject Secrets
        env :
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
        run : |
          sed -i "s/CONSUMER_KEY/$CONSUMER_KEY/g" config.js
          sed -i "s/CONSUMER_SECRET/$CONSUMER_SECRET/g" config.js

      - name: Build
        run: npm install

      - name: Test
        run : npm install -g jest && jest --forceExit --testTimeout=30000
        
      - name: Codecov
        uses: codecov/codecov-action@v1
