name: Test
env:
  AWS_DEFAULT_REGION: "ap-southeast-2"
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: git clone the repo
        uses: actions/checkout@v2

      - name: prep nodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Inject Secrets
        env :
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
        run : |
          sed -i "s/CONSUMER_KEY/$CONSUMER_KEY/g" config.js
          sed -i "s/CONSUMER_SECRET/$CONSUMER_SECRET/g" config.js

      - name: Build
        run: npm install

      - name: Test
        uses: nick-invision/retry@v2
        with:
           timeout_seconds: 60
           max_attempts: 3
           command: node_modules/.bin/jest --forceExit
        
      - name: Codecov
        uses: codecov/codecov-action@v1
